name: Aiven Keep Alive

on:
  schedule:
    # Runs every 12 hours
    - cron: '0 0,12 * * *'
  workflow_dispatch: 

jobs: 
  ping-db:
    runs-on: ubuntu-latest
    steps:
      - name: Install PostgreSQL Client
        run : sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Ping Database
        env:
          DB_URI: ${{ secrets.AIVEN_DB_URI }}
        run: |
          psql "$DB_URI" -c "SELECT 1;"